dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:23453
  enhanced-mode: fake-ip
  default-nameserver:
  - 119.29.29.29
  - 119.28.28.28
  - 1.0.0.1
  - 208.67.222.222
  - 1.2.4.8
  - 114.114.114.114
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fake-ip-range: 198.18.0.1/16
  fallback:
  - https://dns.cloudflare.com/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
  - tls://dot.tiar.app
  fake-ip-filter:
  - "+.*"
